# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: CI
  displayName: 'Fase CI'
  jobs:
  - job: BuildJob
    displayName: 'Trabajo de Compilación'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: CD
  displayName: 'Fase CD'
  dependsOn: CI
  condition: succeeded()
  jobs:
  - deployment: DeployWebApp
    displayName: 'Trabajo de Despliegue'
    environment: 'production'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Aqui van las tareas reales para desplegar en Azure App Service..."
            displayName: 'Paso de despliegue simulado'